### ISSUE TITLE
socks proxy without needing shadowsocks client?

### ISSUE THREAD

**Issue by nearcatch** [wfg/docker-openvpn-client#11]
If I'm understanding how shadowsocks works, after running this container with shadowsocks enabled I would then have to run a shadowsocks client on my target device in order to connect to the proxy, correct? Is there a way to connect to the SOCKS proxy without another piece of software? I was hoping to have it all self-contained inside the container. I was previously using [another container](https://github.com/concision/docker-windscribe-socks-server) for Windscribe but wanted to replace it with yours since this container is more universal. The other one does have a self-contained SOCKS server though.

**Comment by yacht7** [comment]
Today the image contains an optional shadowsocks server. Personally, I haven't tried to connect without the shadowsocks client, but I would expect that it behaves just like any other SOCKS5 proxy. What is your use case?

**Comment by nearcatch** [comment]
I'm trying to use it with this [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/sidebery/), which allows proxying tabs that are in a specified Firefox container. Also have tried to use it in jDownloader. Below are the settings for my extension, jDownloader, and my docker-compose.

```
  vpn-mv1:
    container_name: vpn-mv1
    image: yacht7/openvpn-client
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      t2_proxy:
    ports:
      - 42011:8888
      - 42071:8388
    volumes:
      - /mnt/user/appdata/docker/containers/vpn/mv1:/data/vpn
    environment:
      SUBNETS: "172.17.0.0/16,192.168.7.0/24,192.168.90.1/24,192.168.91.0/24"
      SHADOWSOCKS: "on"
      SHADOWSOCKS_PASS: "$PROXY_PASSWORD"
      TINYPROXY: "on"
      TINYPROXY_USER: "$PROXY_USERNAME"
      TINYPROXY_PASS: "$PROXY_PASSWORD"

```
![Screenshot 2020-11-29 184420](https://user-images.githubusercontent.com/692914/100558186-fb608780-3272-11eb-95b8-d59912d117d3.jpg)
![Screenshot 2020-11-29 183913](https://user-images.githubusercontent.com/692914/100558049-38784a00-3272-11eb-9fa2-be62ea62c633.jpg)
