### ISSUE TITLE
Docker secrets?

### ISSUE THREAD

**Issue by nearcatch** [wfg/docker-openvpn-client#12]
It would be nice if [docker secrets](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) were implemented for the username/password for the proxies.

**Comment by dngray** [comment]
This one is being tested in https://github.com/wfg/docker-openvpn-client/tree/secrets

I was able to verify it works with:

```yaml
services:
  vpn_4:
    extends:
      file: ../docker-vpn/docker-compose-vpn.yml
      service: openvpn-client
    environment:
      - KILL_SWITCH=on
      - SOCKS_PROXY=on
      - HTTP_PROXY=on
      - SUBNETS=192.168.2.1
      - PROXY_USERNAME_SECRET=proxy_username
      - PROXY_PASSWORD_SECRET=proxy_password
    volumes:
      - /mnt/data/container_data/vpn/openvpn-client:/data/vpn
    secrets:
      - proxy_username
      - proxy_password
secrets:
   proxy_username:
     file: ./secrets/proxy_username.txt
   proxy_password:
     file: ./secrets/proxy_password.txt
```

Note you need the kill switch on when using the socks proxy
