### ISSUE TITLE
Compression warning + Exit code 1

### ISSUE THREAD

**Issue by mattiasghodsian** [wfg/docker-openvpn-client#17]
Am getting a Compression warning and the container keeps rebooting giving exit code 1

**VPN provider:** ovpn.com

![screenshot](https://i.imgur.com/vPfpo3f.png)

```yml
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=on
    ports:
      - 8118:8080
      - 1080:1080
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
      - 9117:9117
      - 8989:8989
    volumes:
      - ./config/vpn/config:/data/vpn
    restart: unless-stopped
```
