### ISSUE TITLE
Rotating VPNs

### ISSUE THREAD

**Issue by voboda** [wfg/docker-openvpn-client#33]
I'd like to rotate VPN servers regularly.  Any suggestions?

I tried using a client.conf with multiple remotes and _remote-random_ set to choose a random remote on startup, then used pm2 on the host to pkill openvpn (and also restart the dependent containers so they reconnect) on an interval. But that's proving a bit unreliable. Is there a better way?

Thanks!

**Comment by voboda** [comment]
Found a way using an external cron orchestrator called [deck-chores](https://github.com/funkyfuture/deck-chores): 

Added a container to my docker-compose
```
  officer:
    container_name: officer
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

And then added these labels to the openvpn-client container:
```
   labels:
      deck-chores.rotate-vpn.command: pkill -SIGHUP -x openvpn
      deck-chores.rotate-vpn.interval: 4 minutes

```

This restarts the openvpn process _within_ the container every 4 minutes, which rereads the config file.  Since _remote-random_ is set, it then chooses a new random vpn from the list.

Hope this helps anyone trying to do the same.
