### ISSUE TITLE
write UDP: Operation not permitted (code=1) when KILLSWITCH=on

### ISSUE THREAD

**Issue by yazeed44** [wfg/docker-openvpn-client#35]
Thank you for the great work on this repo.

The container works perfectly when KILLSWITCH is "off", but when it's off I get these errors in the [logs](https://0bin.net/paste/6uXt-IYe#YW+YHf0QAXx2ivx-/R45Lg0yjeSZqNnTAqDDmiXKGmZ)

This is my docker-compose:
```
services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=on
      - SUBNETS=192.168.2.0/24, 192.168.1.0/24
      - HTTP_PROXY=on
      - SOCKS_PROXY=on
      - VPN_LOG_LEVEL=7
    volumes:
      - ./vpn_configs:/data/vpn
    ports:
      - 18080:8080
      - 11080:1080
    dns:
      - 192.168.2.237
    restart: unless-stopped
```

Is this a [firewall issue](https://bbs.archlinux.org/viewtopic.php?id=210534)?
