### ISSUE TITLE
Unrecognized option or missing or extra parameter(s) in /data/vpn/passfile.conf.modified

### ISSUE THREAD

**Issue by gratefulbread** [wfg/docker-openvpn-client#61]
I'm getting the following error when I try to start the container.

> Unrecognized option or missing or extra parameter(s) in /data/vpn/passfile.conf.modified:1: (redacted PIA username) (2.5.6)

my compose file:
```
version: '3'

services:
  vpn:
    image: ghcr.io/wfg/openvpn-client
    privileged: true
    container_name: openvpn-client
    cap_add: 
      - NET_ADMIN
    devices: 
      - /dev/net/tun:/dev/net/tun
    environment:
      - SUBNETS=192.168.1.0/24
      - HTTP_PROXY=on
      - SOCKS_PROXY=on
      volumes: 
      - /share/Docker/ovpn/config:/data/vpn
```

my conf
```
client
dev tun
proto udp
remote us-california.privacy.network 1198
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-128-gcm
ncp-disable
tls-client
remote-cert-tls server

auth-user-pass passfile
compress
verb 1
reneg-sec 0
<crl-verify>
-----BEGIN X509 CRL-----
xxxxx
-----END X509 CRL-----
</crl-verify>

<ca>
-----BEGIN CERTIFICATE-----
xxxxx
-----END CERTIFICATE-----
</ca>

disable-occ
```
