### ISSUE TITLE
No configuration file found. Please check your mount and file permissions. Exiting.

### ISSUE THREAD

**Issue by joelstitch** [wfg/docker-openvpn-client#62]
I followed the instructions for installing this docker container but whenever I run it I keep getting this error:

`No configuration file found. Please check your mount and file permissions. Exiting.`

I mapped the folder as per the directions and added the ovpn file and passfile but I just keep getting this error. I tried putting the files in a /config folder and /vpn folder but that didnt work neither.

This is my docker-compose.yml

```
services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 6077:6077
    volumes:
      - /volume1/docker/openvpn:/data/vpn
    restart: unless-stopped
    
```
