### ISSUE TITLE
Since v3 not working

### ISSUE THREAD

**Issue by MartinHotmann** [wfg/docker-openvpn-client#66]
I today updated my VPN image to v3.0.0 (just relased) and my previous setup, which workled perfectly fine is now not working anymore.

There is nothing I changed. After reverting back to 2.1.1 everything works again.

Is there something I need to do when upgrading to v3.0.0?

Errorlos just shows this: `config/nftables.conf:31:1-93: Error: Could not process rule: Invalid argument` repeatingly

**Comment by MartinHotmann** [comment]
Thanks, that is probably the reason why the command `nft -f config/nftables.conf` utilizes 100% of my CPU and made the NAS unusable :P

Does this command need to be executed before or after the upgrade?

**Comment by MartinHotmann** [comment]
here the output (when executed on v3):

```
#!/usr/bin/nft

flush ruleset

# base ruleset
add table inet killswitch

add chain inet killswitch incoming { type filter hook input priority 0; policy drop; }
add rule inet killswitch incoming ct state established,related accept
add rule inet killswitch incoming iifname lo accept

add chain inet killswitch outgoing { type filter hook output priority 0; policy drop; }
add rule inet killswitch outgoing ct state established,related accept
add rule inet killswitch outgoing oifname lo accept

# allow traffic to/from the Docker subnet
add rule inet killswitch incoming ip saddr 172.22.0.0/16 accept
add rule inet killswitch outgoing ip daddr 172.22.0.0/16 accept

# allow traffic to the VPN server(s)
add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.168.167.236 udp dport 1151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.232 udp dport 1151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 95.211.95.244 udp dport 1151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 37.48.94.1 udp dport 1151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.64.131 udp dport 1151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 151 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 1148 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 1149 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 1150 accept

add rule inet killswitch outgoing oifname eth0 ip daddr 85.17.28.145 udp dport 1151 accept

# allow traffic over the VPN interface
add rule inet killswitch incoming iifname tun0 accept
add rule inet killswitch outgoing oifname tun0 accept
```

**Comment by MartinHotmann** [comment]
I start the container with docker compose.

the compose file is this:

```
version: "3.8"
services:
  vpn:
    image: ghcr.io/wfg/openvpn-client:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=on
      - VPN_CONFIG_FILE=PerfectPrivacy/Frankfurt.ovpn
    volumes:
      - "/volume1/docker/config/vpn/:/data/vpn"
    restart: unless-stopped
```

On none of my Synos and servers the v3 is working as it throws the error mentioned above. But on one NAS (also Syno) it even makes it ununable.

**Comment by wfg** [comment]
Strange. That's basically exactly how I run it as well without issue.

Can you run this inside the container AND on the host itself and share the outputs?
```
lsmod | grep nf_tables
```

**Comment by MartinHotmann** [comment]
## Syno1
Host:
-- empty --

Container v2.1.1:
-- empty --

Container v3.0.0:
(not executed, as otherwise NAS again unusable)


## Syno2
Host:
-- empty --

Container v2.1.1:
-- empty --

Container v3.0.0:
(not executed, as otherwise NAS again unusable)

Is it the wrong command or is "nothing" to be expected?

**Comment by mindset-tk** [comment]
I am getting a similar error.
`config/nftables.conf:25:83-87: Error: syntax error, unexpected dport
add rule inet killswitch outgoing oifname eth0 ip daddr [redacted] tcp-client dport [redacted] accept`

The container restarts infinitely so I don't seem to be able to pull nf_tables.

In case it matters, my vpn.conf file looks like. As far as I understand this is a standard unified format, but please let me know if I futzed something.

`client
proto tcp-client
remote [ip.v4.add.ress] [port]
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_4FaNHU1cFptzTGUl name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
<ca>
-----BEGIN CERTIFICATE-----`

**Comment by MartinHotmann** [comment]
After going back to `image: ghcr.io/wfg/openvpn-client:2.1.1` nothing works anymore. Even the old v2.1.1 not.

**Comment by wfg** [comment]
It’s the nftables change. It looks like the underlying hosts also need to be using nftables for the container to use it.

I’ll dig more into it soon. Until then, try a 2.x version.

**Comment by MartinHotmann** [comment]
> I’ll dig more into it soon. Until then, try a 2.x version.

Thanks.

Do we get a "`2`" branche, so we can go with `image: ghcr.io/wfg/openvpn-client:2` to always get the latest v2 if there will be any updates.
General setting up the major versions as branches would be a good idea so when v4 comes out the folks who chose "`3`" will not automatically get updated to v4 and may got they setup broken.

**Comment by wfg** [comment]
> Do we get a "`2`" branche, so we can go with `image: ghcr.io/wfg/openvpn-client:2` to always get the latest v2 if there will be any updates. General setting up the major versions as branches would be a good idea so when v4 comes out the folks who chose "`3`" will not automatically get updated to v4 and may got they setup broken.

Well I did bump the major version here (2 -> 3), which indicates there are breaking changes. I can't help if people use the tag `latest` ;)

You can see the existing tags here: https://github.com/wfg/docker-openvpn-client/pkgs/container/openvpn-client

**Comment by MartinHotmann** [comment]
Aaaah and I always looked at the wrong place :P

**Comment by mindset-tk** [comment]
> It’s the nftables change. It looks like the underlying hosts also need to be using nftables for the container to use it.
>
> I’ll dig more into it soon. Until then, try a 2.x version.

Understandable, 2.1.1 working great here.  I'll just update my compose to the effect for now.

**Comment by wfg** [comment]
@MartinHotmann @mindset-tk if either one of you could try 3.0.0 once more and send me the output of `lsmod` from inside the container, that would be helpful. And tell me what host OS and version you're running.

**Comment by dngray** [comment]
So I seem to be having some trouble with `SUBNETS` with the new 3.0.0 builds. My host is also alpine linux.

`container logs` reveals this error:

```
--- Running with the following variables ---
VPN configuration file: vpn_config.ovpn
Use default resolv.conf: on
Allowing subnets: 172.18.0.0/16
Kill switch: on
Using OpenVPN log level: 3
---

info: original configuration file: vpn/vpn_config.ovpn
info: modified configuration file: vpn/openvpn.NHJQuqYR.conf
info: kill switch is on
RTNETLINK answers: File exists
```

Finally it ends with:

```
Creating vpn_bittorrent ... done
Creating qbittorrent    ... error

ERROR: for qbittorrent  Cannot start service qbittorrent: Container c86109750892e8ba892a179ede48666d6fb36d79dff6589a0045cc6ce7132644 is restarting, wait until the container is running

ERROR: for qbittorrent  Cannot start service qbittorrent: Container c86109750892e8ba892a179ede48666d6fb36d79dff6589a0045cc6ce7132644 is restarting, wait until the container is running
ERROR: Encountered errors while bringing up the project.
```

My `docker-compose.yml` looks like this:

```yaml
services:
  vpn_bittorrent:
    extends:
      file: ../vpn/container-compose.yml
      service: openvpn-client
    container_name: vpn_bittorrent
    volumes:
      - /mnt/data/container_data/vpn:/data/vpn
    ports:
      - xxxxxx:xxxxxx
      - yyyyyy:yyyyyy/udp
      - 8081:8081/tcp
    environment:
      - SUBNETS=172.18.0.0/16
      - KILL_SWITCH=on
      - VPN_CONFIG_FILE=vpn_config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$MY_DOMAIN`)"

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn_bittorrent
    environment:
      - PUID=1003
      - PGID=1004
      - WEBUI_PORT=8081
    volumes:
      - /mnt/data/container_data/qbittorrent:/config
      - /mnt/data/shared/incoming:/mnt/shared/incoming
    restart: unless-stopped

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
```

The common part of the container is just:

```yaml
services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    #build:
    #  context: ./docker-openvpn-client
    #  dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
```

**Comment by adr3nal1n** [comment]
I am using docker version 20.10.17 and the host OS is Debian v11 Bullseye.

I had the same issue with v3 and the container just kept restarting and I found lots of copies of .conf files (owned by root) in the config folder on my host that were time stamped from the various attempts. Normally on v2.1.1 it would copy my openvpn.conf file and create a file called openvpn.conf.modified

I then did a docker stop openvpn-client, followed by a docker rm openvpn-client and finally I deleted the image using docker rmi ghcr.io/wfg/openvpn-client:latest

I then modified  my compose file to point to config 2.1.1 and then rebuilt the container and v2.1.1 worked as before.

I then stopped the v2.1.1 container, deleted it and the image, modified the compose file to point to v3 and then rebuilt the container again. This time the v3 container came up first time and it copied my openvpn.conf file to a file called openvpn.3uqHskTH.conf (owned by root)

Output from lsmod inside the v3 container is:
[lsmod_output_from_v3_container.txt](https://github.com/wfg/docker-openvpn-client/files/8934133/lsmod_output_from_v3_container.txt)

Logfile for the v3_container is:
[v3_container_log.txt](https://github.com/wfg/docker-openvpn-client/files/8934170/v3_container_log.txt)

Hope the above information helps in some way. I'll keep running the v3 container for now and let you know if I notice anything odd.

**Comment by lkracon** [comment]
Similar problem here. After docker start I'm getting following errors:
`proxy_3_1  | config/nftables.conf:21:57-69: Error: Hostname resolves to multiple addresses
proxy_3_1  | add rule inet killswitch outgoing oifname eth0 ip daddr nl.prcdn.net. udp dport 553 accept
proxy_3_1  |                                                         ^^^^^^^^^^^^^
proxy_3_1  | config/nftables.conf:23:57-73: Error: Hostname resolves to multiple addresses
proxy_3_1  | add rule inet killswitch outgoing oifname eth0 ip daddr ams-nl.prcdn.net. udp dport 553 accept
proxy_3_1  |                                                         ^^^^^^^^^^^^^^^^^` 

Going back to v 2.1.1 solves the problem.

**Comment by adr3nal1n** [comment]
V3 is still working and running healthy for the last 5 days,

If you are having issues, maybe try the following as it worked for me:

1. docker stop openvpn-client
2. docker rm openvpn-client
3. docker rmi ghcr.io/wfg/openvpn-client:latest
4. Recreate the openvpn-client container

**Comment by mindset-tk** [comment]
> @MartinHotmann @mindset-tk if either one of you could try 3.0.0 once more and send me the output of `lsmod` from inside the container, that would be helpful. And tell me what host OS and version you're running.

Sorry for the delay.  I had to do something a little hacky to make this work, since the container wanted to reboot infinitely and prevented me from running lsmod.

I set it to run the following script at startup instead of the standard entrypoint. all it does is force the container to stay running after completing the standard

```
#!/bin/sh
scripts/entry.sh
while true; do sleep 1; done
```
then I was able to get in and run lsmod:
[lsmod.txt](https://github.com/wfg/docker-openvpn-client/files/8979076/lsmod.txt)

**Comment by dngray** [comment]
There defintely seems to be *an* issue.

In this case I did a `docker system prune -a` and pruned back to nothing.

I deleted all the VPN configs, and tried again:

```
doas docker-compose up

...

Status: Downloaded newer image for ghcr.io/linuxserver/qbittorrent:latest
Creating vpn_bittorrent ... done
Creating qbittorrent    ... error

ERROR: for qbittorrent  Cannot start service qbittorrent: Container 7dd9ebe1e952dfe5bb46c9907fd29b496985c80b02b1534b76540dc2283b27f8 is restarting, wait until the container is running

ERROR: for qbittorrent  Cannot start service qbittorrent: Container 7dd9ebe1e952dfe5bb46c9907fd29b496985c80b02b1534b76540dc2283b27f8 is restarting, wait until the container is running
ERROR: Encountered errors while bringing up the project.
```

I tried this with a simpler setup:

```yaml
services:
  vpn_test:
    extends:
      file: ../vpn/container-compose.yml
      service: openvpn-client
    container_name: vpn_test
    volumes:
      - /mnt/data/container_data/vpn:/data/vpn
    ports:
      - 8123:8123/tcp
    environment:
      - KILL_SWITCH=on
      - SUBNETS=172.18.0.0/16
      - VPN_CONFIG_FILE=vpn_config_name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.tls=true"
      - "traefik.http.routers.test.entrypoints=websecure"
      - "traefik.http.routers.test.rule=Host(`test.$MY_DOMAIN`)"

  test:
    image: busybox
    container_name: test
    network_mode: service:vpn_test
    command: httpd -f -p 8123 -h /etc/

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
```

Things seemed to work in that.
```
vpn_test    | --- Running with the following variables ---
vpn_test    | VPN configuration file: vpn_config_name
vpn_test    | Use default resolv.conf: on
vpn_test    | Allowing subnets: 172.18.0.0/16
vpn_test    | Kill switch: on
vpn_test    | Using OpenVPN log level: 3
vpn_test    | ---
vpn_test    | 
vpn_test    | info: original configuration file: vpn/vpn_config_name
vpn_test    | info: modified configuration file: vpn/openvpn.JkFtDPdc.conf
vpn_test    | info: kill switch is on
...
```

**Comment by dngray** [comment]
So I removed the qbittorrent section, did a system prune and just had:

```yaml
services:
  vpn_bittorrent:
    extends:
      file: ../vpn/container-compose.yml
      service: openvpn-client
    container_name: vpn_bittorrent
    volumes:
      - /mnt/data/container_data/vpn:/data/vpn
    ports:
      - 26129:26129
      - 26129:26129/udp
      - 8081:8081/tcp
    environment:
      - KILL_SWITCH=on
      - SUBNETS=172.18.0.0/16
      - VPN_CONFIG_FILE=vpn_config_name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$MY_DOMAIN`)"
```

When starting I get:

```
Creating vpn_bittorrent ... done
Attaching to vpn_bittorrent
vpn_bittorrent    | 
vpn_bittorrent    | --- Running with the following variables ---
vpn_bittorrent    | VPN configuration file: vpn_config_name
vpn_bittorrent    | Use default resolv.conf: on
vpn_bittorrent    | Allowing subnets: 172.18.0.0/16
vpn_bittorrent    | Kill switch: on
vpn_bittorrent    | Using OpenVPN log level: 3
vpn_bittorrent    | ---
vpn_bittorrent    | 
vpn_bittorrent    | info: original configuration file: vpn/vpn_config_name
vpn_bittorrent    | info: modified configuration file: vpn/openvpn.a7i9rIWP.conf
vpn_bittorrent    | info: kill switch is on
vpn_bittorrent    | RTNETLINK answers: File exists
```

In between these tests I did a `system prune -a` Using the same config, I made sure to clear out the openvpn.*.conf files.
