### ISSUE TITLE
useradd: command not found in v3

### ISSUE THREAD

**Issue by OceanApart** [wfg/docker-openvpn-client#69]
```yaml
services:
    openvpn-client:
        image: ghcr.io/wfg/openvpn-client:latest
        container_name: openvpn-client
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
            - KILL_SWITCH=off
            - VPN_CONFIG_FILE=my.ovpn
            - VPN_LOG_LEVEL=5
            - SOCKS_PROXY=true
            - SOCKS_PROXY_USERNAME=username
            - SOCKS_PROXY_PASSWORD=pwd
        ports:
            - 10800:1080 # socks
        volumes:
            - ./config:/data/vpn
        restart: unless-stopped
        network_mode: bridge
```

v3 got following error:

```
openvpn-client    | 2022-06-26 01:37:33 us=901487 Initialization Sequence Completed
openvpn-client    | info: starting socks proxy with credentials
openvpn-client    | Wscripts/run-socks-proxy.sh: line 16: useradd: command not found
```

Fixed by running `apk add shadow` in container and restart. But there is warning for your attention.

```
openvpn-client    | WJun 26 02:03:34 (1656209014.646418) sockd[18]: warning: config/socks-proxy.conf: problem on line 7 near token "method": keyword "method" is deprecated - assuming the new keyword "socksmethod" was meant.  Please update Dante's config file (config/socks-proxy.conf) to use the new keyword as appropriate.  Please see the Dante manual for more information
```
