### ISSUE TITLE
Handling ports intended for connected containers Doesn't work.

### ISSUE THREAD

**Issue by xky0007** [wfg/docker-openvpn-client#71]
I tried to access the nginx server that in a same docker stack with open-vpn. Below is my docker-compose.yml.
I cannot open nginx page via http://localhost:8001.
But I checked listening ports, 8001 is LISTEN.
Is there any config I missed?

Thanks.
```
version: '3'
services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /home/ubuntu/open-vpn docker/config:/data/vpn 
    restart: unless-stopped
    ports:
    - "8001:80"
    environment:
    - KILL_SWITCH=off


  nginx:
    image: nginx
    container_name: nginx_test
    network_mode: service:openvpn-client
```
