### ISSUE TITLE
IP & DNS ptr leaked

### ISSUE THREAD

**Issue by MartinHotmann** [wfg/docker-openvpn-client#76]
Just run a bunch of tests with some friends of mine and it turns out they are able to detect and provide me with my DNS ptr on the first boot. At later reboots (docker restart [container]) this does not seem to happen anymore.

The PTR was correct and directly points to my server (ofc it does it is an IP reverse lookup). But this also means they had my servers IP. Apparently I can't say if this is true for IPv6 aswell since I have turned it off for now.

But that is not good. I also can't say if it is a docker core problem or the problem of this image. But what I can expose is my censored docker-compose.yml:

```
version: "3"
services:
  vpnFRA:
    image: ghcr.io/wfg/openvpn-client:latest
    container_name: vpnFRA
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=on
      - VPN_CONFIG_FILE=Frankfurt.ovpn
      - LANG=de_DE.UTF-8
    ports:
      - 127.0.0.1:5805:5805
    volumes:
      - "/data/vpn:/data/vpn"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped

  app1:
    image: [CENSORED]
    container_name: app1
    network_mode: "container:vpnFRA"
    environment:
      - PUID=10004
      - PGID=33
      - TZ=Europe/Berlin
      - LANG=de_DE.UTF-8
    volumes:
      - "/config:/config:rw"
      - "/storage:rw:/storage:rw"
    restart: unless-stopped
    depends_on:
      - vpnFRA
```

`KILL_SWITCH=on` should have prevented ALL IP leaks, but it did not. But what I noticed on the first `docker-compose up -d` is this:

the container `app1` starts first, then the VPN container and then `app1`. Anyway this should have never had any internet access as it's network_mode (container:vpnFRA) was not fully booted yet?

The DNS PTR is automatically detected (if detectable) and I was this multiple times and don't like that others can track my server behind a dockerized VPN container. I am pretty sure I have not seen this before with v2, but since some things changed in the meantime, I can not tell for sure where the culprit is. But at first boot something happens that exposes (or gives the chance of exposing the servers IP!).

Hope to hear back :)

**Comment by wfg** [comment]
Thanks for bringing this up @MartinHotmann. It is important to me that my image does what it advertises at the very least. :)

To try to narrow down possible causes, can you run a similar test where `vpnFRA` is already running and then you start `app1`?

**Comment by MartinHotmann** [comment]
I will try to do and ask them if it then still exposes the IP.

But since it is set as "`depends_on`" it should just start after `vpnFRA` is running. But maybe that is a docker issue? Will do some more tests and come back.

**Comment by MartinHotmann** [comment]
> can you run a similar test where `vpnFRA` is already running and then you start `app1`?

It was not reproducable, when the vpnFRA was running already. Just on first creation time. So if you "`docker stop vpnFRA && docker rm vpnFRA`", then it will be reproducable.

**Comment by twiebe** [comment]
I also encountered potential leaking during testing and traced it back to the killswitch setup procedure, which resolves remotes ony by one, before dropping traffic through the unsecure `eth0` interface.

In my case the list of remotes was quite long and dns resolving took a few seconds per remote (for unknown reasons at this point), so the time period in which other containers were communication unsecured was a few minutes.

I made a fix in a fork [here](https://github.com/wfg/docker-openvpn-client/commit/fc7c0ce3a589f6fab029e2b7aecffc66c29b08d6) which I'm currently testing. The fix drops all traffic that is not explicitly allowed immediately, before performing the dns lookups. To still allow the lookups to function in any potential container dns configuration resp. for potentially external dns resolvers, iptables allow rules are added temporarily until the lookups are done.

Looks promising so far for what I encountered. Not sure if it addresses your problem @MartinHotmann, but if you want to check it out, you can either build your own image from that code or use the build [here](https://github.com/twiebe/docker-openvpn-client/pkgs/container/docker-openvpn-client).

**The fix is only implemented for iptables so far.** If it proves to solve the issue, I'll open a PR and perhaps look into how to solve it for nftables, too.

**Comment by wfg** [comment]
> ...traced it back to the killswitch setup procedure, which resolves remotes ony by one, before dropping traffic through the insecure eth0 interface.
> 
> In my case the list of remotes was quite long and dns resolving took a few seconds per remote (for unrelated reasons), so the time period in which other containers were communicating insecurely was as long as a few minutes.
> ...

When I read what @MartinHotmann wrote, I had a feeling this was what was going on here. Have you been using it with this change over the past few days? Does it seem to be working as expected?

**Comment by MartinHotmann** [comment]
@twiebe servus Thomas und danke für den QuickFix!

I will perform some tests the next days and will report back if it entirely fixed the problem for me or not.

Thanks in advance!

**Comment by twiebe** [comment]
> When I read what @MartinHotmann wrote, I had a feeling this was what was going on here. Have you been using it with this change over the past few days? Does it seem to be working as expected?

Yep, it's been running like that for a few days and all manual checks look good so far. However, since I'm traveling at the moment, I have only found little time to do testing. Will do some more on the weekend once I'm back and open the PR, even if just for iptables yet.

BTW: This morning I've made a small adjustment to not bind the temporary resolver rules to `eth0`, but instead to all interfaces. Custom `bridge` docker network (can) have `127.0.0.0/8` ip addresses on the `lo` interface as resolvers. (though technically it already worked before, since the `lo` interface has the `ACCEPT` rules in both directions)

**Comment by twiebe** [comment]
Did some further testing and everything worked as expected. Here's the PR for the iptables fix: https://github.com/wfg/docker-openvpn-client/pull/80

Hope that it fixes your issues, too, @MartinHotmann. ✌️

**Comment by twiebe** [comment]
Excellent. Glad it helped!

**Comment by MartinHotmann** [comment]
Dunno if related to this here, but ATM the container does not start and completely leaks all and everything.
Running the latest version.

@wfg

**Comment by wfg** [comment]
I just tested latest with this Compose file and everything works as expected
```
services:
  vpn:
    image: ghcr.io/wfg/openvpn-client:latest
    container_name: ovpn-test
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    environment:
    - SUBNETS=192.168.10.0/24
    volumes:
     - ./.local/vpn:/data/vpn
```

**Comment by MartinHotmann** [comment]
Thanks for the reply! I will again dig into and see what I can do.

**Comment by wfg** [comment]
Unrelated, but given that sysctl, you're using ipv6. Does this image work well with that?

**Comment by MartinHotmann** [comment]
I just founf out what it was.

The OVPN files from the provider have been updated and the the old ones have not been valid anymore. At the next restart of the container no connection was established.

For now the problem is fixed by updating the files and then restarting the container.

But the container really should not allow any connection without having a VPN connection established. Guess he somewhere fails silently and sallows connected containers to be reached.
Dont know if @twiebe's PR here https://github.com/wfg/docker-openvpn-client/pull/80 could have fixed it or not, as I again am on the official version.

**Comment by wfg** [comment]
@MartinHotmann I have something for you to test if you're willing.

1. Build the [rewrite](https://github.com/wfg/docker-openvpn-client/tree/rewrite) branch using the `build` directory as the context.
    ```
    docker build -t ovpn-test https://github.com/wfg/docker-openvpn-client.git#rewrite:build
    ```
2. Test with a Compose file similar to the following:
    ```yaml
    services:
      ovpn-test:
        image: ovpn-test
        container_name: ovpn-test
        cap_add:
        - NET_ADMIN
        devices:
        - /dev/net/tun:/dev/net/tun
        environment:
        - ALLOWED_SUBNETS=192.168.10.0/24
        volumes:
        - ./local/vpn:/data/vpn
    ```

I'd like to see how it behaves with the old config and with the new config to see if either leaks.
